class AlreadyExistExeption(Exception):
    pass

class FailureAuthenticationException(Exception):
    pass
